#! php

<?php

use Acme\AddCommand;
use Acme\CompleteCommand;
use Acme\ShowCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Task app', '1.0');

try {
    $pdo = new PDO('mysql:dbname=command', 'root');

    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $exception) {
    echo 'Could not connect to the database';
    exit(1);
}
$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new Showcommand($dbAdapter));
$app->add(new AddCommand($dbAdapter));
$app->add(new CompleteCommand($dbAdapter));

$app->run();